# Default update config
# Config order: hparams_registry -> config.yaml -> CLI

ffcv: True
use_amp: True
test_batchsize: 128
indomain_test: False  # use indomain test split or not
drop_mode: 'filter'
drop_activation: False
drop_noise: False
rx: True